### ISSUE TITLE
Add support for room guid's

### ISSUE THREAD

**Issue by saerdnaer** [pretalx/pretalx-downstream#5]
As organizer in an upstream system I'd like to be able to rename rooms, without duplicating them downstream. 

Right now the room get's created downstream as new room instead of renaming the existing one, as seen on pertalx.c3voc.de during jev22 when `Sparti` was renamed to `RTC-Bühne (Sparti)`

Additional complication: When the upstream and downstream conferences are in the same pretalx instance, there might be conflicts depending on how the unique constrains in the database are set...

**Comment by rixx** [comment]
Two notes:

- This plugin is very much intended to be a showcase plugin, with absolutely zero support offered, and no compliance guarantees.
- The room GUID feature is new (in pretalx), second-class, and something I already regret adding due to the added maintenance burden it has placed on me, due to incomplete PRs and even more incomplete integration.

For these reasons, it's likely that I'd merge a PR against this plugin adding GUID support, but I'm closing the issue to indicate that I have no plans to implement this, and that I do not consider it important to the functioning of this plugin.
