### ISSUE TITLE
Allow empty/non-existing description on `<event>`

### ISSUE THREAD

**Issue by saerdnaer** [pretalx/pretalx-downstream#6]
The https://c3voc.de/schedule/schema.xsd defines `<description>` on `<event>` as optional, but the plugin fails if the attribute is missing.

/cc @Kunsi

**Comment by rixx** [comment]
First off, this plugin claims no compatibility with `schema.xsd`.

Secondly: *please* provide details rather than saying "the plugin fails" – what does that mean?. Is there a stacktrace? Is there a logged error? Is there just no update? How does the last update date behave? And so on.

(No need to provide these details now, I simply guessed what might happen and made the code more resilient, but I'd really prefer it if I didn't have to do that.)
